### ISSUE TITLE
Guardian/Pet creatures hp not scaling

### ISSUE THREAD

**Issue by duncrafter** [azerothcore/mod-autobalance#101]
Currently most summoned creatures (Guardians/Pets etc.) health is not scaling properly.
Example: Lupine Delusions in SFK, Remote-Controlled Golems in DM/EVC

**Comment by duncrafter** [comment]
[https://github.com/azerothcore/azerothcore-wotlk/issues/9291](url)
Probably the reason

**Comment by Mitradis** [comment]
class AutoBalance_AllCreatureScript : public AllCreatureScript
{
public:
    AutoBalance_AllCreatureScript()
        : AllCreatureScript("AutoBalance_AllCreatureScript")
    {
    }

just add this:
    void OnCreatureAddWorld(Creature* creature)  override
    {
        if (!enabled)
            return;

        ModifyCreatureAttributes(creature, true);
    }

**Comment by CanadianMath** [comment]
Can we fix this by manually adding things to a list?

**Comment by CanadianMath** [comment]
> 

Oh, is that bottom text just added to the AutoBalance.cpp under the above? Seems shockingly simple.

**Comment by duncrafter** [comment]
Yes, with a two-line space between. My knowledge of C++ is _very_ limited, but I think this starts the code for attribute modification when a creature is added to the world?

**Comment by cdenq** [comment]
This issue is still persistent as of 2023.

Likewise, testing out the changes suggested by the deleted post, the following error occurs when building the server:
```
15>C:\AzerothCore\modules\mod-autobalance\src\AutoBalance.cpp(1913,10): error C2535: 'void AutoBalance_AllCreatureScript::OnCreatureAddWorld(Creature *)': member function already defined or declared
15>C:\AzerothCore\modules\mod-autobalance\src\AutoBalance.cpp(1892,10): message : see declaration of 'AutoBalance_AllCreatureScript::OnCreatureAddWorld'
15>C:\AzerothCore\modules\mod-autobalance\src\AutoBalance.cpp(1894,10): error C2065: 'enabled': undeclared identifier
15>C:\AzerothCore\modules\mod-autobalance\src\AutoBalance.cpp(1897,9): error C2660: 'AutoBalance_AllCreatureScript::ModifyCreatureAttributes': function does not take 2 arguments
15>C:\AzerothCore\modules\mod-autobalance\src\AutoBalance.cpp(2058,10): message : see declaration of 'AutoBalance_AllCreatureScript::ModifyCreatureAttributes'
15>C:\AzerothCore\modules\mod-autobalance\src\AutoBalance.cpp(1897,9): message : while trying to match the argument list '(Creature *, bool)'
```

**Comment by pangolp** [comment]
> This issue is still persistent as of 2023.
> 
> Likewise, testing out the changes suggested by the deleted post, the following error occurs when building the server:
> ```
> 15>C:\AzerothCore\modules\mod-autobalance\src\AutoBalance.cpp(1913,10): error C2535: 'void AutoBalance_AllCreatureScript::OnCreatureAddWorld(Creature *)': member function already defined or declared
> 15>C:\AzerothCore\modules\mod-autobalance\src\AutoBalance.cpp(1892,10): message : see declaration of 'AutoBalance_AllCreatureScript::OnCreatureAddWorld'
> 15>C:\AzerothCore\modules\mod-autobalance\src\AutoBalance.cpp(1894,10): error C2065: 'enabled': undeclared identifier
> 15>C:\AzerothCore\modules\mod-autobalance\src\AutoBalance.cpp(1897,9): error C2660: 'AutoBalance_AllCreatureScript::ModifyCreatureAttributes': function does not take 2 arguments
> 15>C:\AzerothCore\modules\mod-autobalance\src\AutoBalance.cpp(2058,10): message : see declaration of 'AutoBalance_AllCreatureScript::ModifyCreatureAttributes'
> 15>C:\AzerothCore\modules\mod-autobalance\src\AutoBalance.cpp(1897,9): message : while trying to match the argument list '(Creature *, bool)'
> ```

I'll try to check it tomorrow.
