### ISSUE TITLE
Simple install instructions........

### ISSUE THREAD

**Issue by Freejack01** [azerothcore/mod-autobalance#104]
Simple instructions for this specific mod would be nice. I have it but I have no clue if it is installed. Not sure where what goes and unsure if or how to compile since the cmakelist.txt does not exist.

Again simple instructions would be nice.

**Comment by kjack9** [comment]
This sounds like a more general request for installing modules in general, not just `mod-autobalance`. AB isn't installed materially differently from any other AzerothCore module.

https://www.azerothcore.org/wiki/installing-a-module

If you have specific information you're looking for that isn't covered in that guide, please re-open this Issue and provide details on what you'd like to see. I'm closing this as wontfix for now.
