### ISSUE TITLE
Latest Core Update Breaking Changes

### ISSUE THREAD

**Issue by jshplayer** [azerothcore/mod-autobalance#121]
Commit e5665c32f880c6887f8dc955a0760bb8ac620bea has made changes to DB (LFGDungeons) breaking autobalance - it no longer compiles.

**Comment by 127y** [comment]
@jshplayer 

I think it can be modified like this. I don't know if it's correct

        max  = dungeon->TargetLevel ? dungeon->TargetLevel : dungeon->MaxLevel;

**Comment by jshplayer** [comment]
thanks yeah i've applied that alongside MinLevel changes, just confirming new compiler error though as it's still failing.

**Comment by AnchyDev** [comment]
I'll have a PR up in a bit.

**Comment by jshplayer** [comment]
module now compiles with anchy's above PR however does not seem to actually scale when inside a dungeon anymore.
