### ISSUE TITLE
AutoBalance.DungeonsOnly=0

### ISSUE THREAD

**Issue by alaxandir** [azerothcore/mod-autobalance#126]
Whenever utilizing the conf settings 
`AutoBalance.DungeonsOnly=0` in combination with the settings `AutoBalance.levelUseDbValuesWhenExists = 1` 
and `AutoBalance.levelScaling=1`

Produces a very strange effect on all game objects (creatures and NPCS). They appear to have 0 Hitpoints and are interpreted as "dead" by the game client and therefore non-interactable, however I believe they are actually alive with 'nil' hitpoints. Critters and monsters with wander still move around as if they were alive.

Checking the stats with the built in .ab command reveals the health multiplier is `nil` on aforementioned creatures.

Bug was observed on a fresh server with a level 61 shaman, goldshire specifically but when teleported to other zones, instantly produced similar results.

**Comment by kjack9** [comment]
Thank you for your report! I apparently did not do enough testing with `AutoBalance.DungeonsOnly=0`. I will spin up a fresh server and work on this ASAP. For now, you can set `AutoBalance.DungeonsOnly=1` to workaround the issue.
