### ISSUE TITLE
Bug: Scaling based on player level

### ISSUE THREAD

**Issue by jshplayer** [azerothcore/mod-autobalance#137]
### Current Behaviour

Mobs are scaling both HP and attack etc based on player level - this was previously not the case and makes classic dungeons much harder for players. Note "level scaling" is disabled.

### Expected Behaviour

Mob HP and stats should be unaffected by player levels.

### Steps to reproduce the problem

1. Enter dungeon and change your level
2. Watch mobs adjust their scaling

### AC rev. hash/commit

AzerothCore rev. bb8239e33319+ 2023-06-25 11:58:35 +1200 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian 10

**Comment by kjack9** [comment]
Hi there! I'm investigating this bug right now and I think I know what's causing it.

Just to confirm, can you give me an example where you're seeing this specific issue? What level are you and what dungeon are you in? Are you using `.ab creaturestat` to confirm?

Thanks for your report.

**Comment by jshplayer** [comment]
Hey thanks for coming back to us. I tried this in multiple dungeons with the same effect:
RDF into any dungeon as a GM with GM mode off as a e.g. lvl 50.
View mob HP.
..character level 60 or 70 or 80.
Watch their HP immediately climb and their hit damage increase (sorry haven't used creaturestat, can only assume all stats have scaled)

**Comment by kjack9** [comment]
> Hey thanks for coming back to us. I tried this in multiple dungeons with the same effect: RDF into any dungeon or "tele zg" as a raid example, go in as a GM with GM mode off as a e.g. lvl 60. View mob HP. .character level 70 or 80. Watch their HP immediately climb and their hit damage increase (sorry haven't used creaturestat, can only assume all stats have scaled)

I think I've already got it fixed in my PR, but can you confirm that the HP/damage stays the same if you test with level 30 and level 50 for an instance? You shouldn't only see the issue when you switch between the level ranges of expansions.
