### ISSUE TITLE
Bug: Fixed money reward not splitting off max players [NPCBots fork]

### ISSUE THREAD

**Issue by Dreathean** [azerothcore/mod-autobalance#140]
### Current Behaviour

Hello, I'm using Trickerer's fork https://github.com/trickerer/mod-autobalance/tree/npcbots_3.3.5 as I'm using NPCBots so I'm not certain if this issue is specifically from his fork or in the base module, but when using "Fixed" reward scaling in a 40 man raid, we (2 players, 8 npcbots) are receiving the full gold split by 2 instead of split by 40. This was noted in multiple raids.

### Expected Behaviour

Gold should be split by the maximum players in a given dungeon/raid and so should be split by 40 before being received by the player.

### Steps to reproduce the problem

Kill raid boss using "fixed" money scaling

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/30197f4

### Operating system

Windows 11

### Custom changes or Modules

NPCBots Azerothcore fork
Autobalance NPCBots fork

**Comment by kjack9** [comment]
Hi there. You'll need to submit this to Trickerer, as I imagine we're not counting the NPCBots as "players" when the XP/gold are split.
