### ISSUE TITLE
Bug: Auto-Scaling of Summoned Pets in Dungeons Do Not Scale

### ISSUE THREAD

**Issue by cdenq** [azerothcore/mod-autobalance#146]
### Current Behaviour

For eg. Voidwalkers in Ragefire Chasms summoned by the orcs, the boars of the hunters in Razorfen Kraul.

These summoned creatures do not properly scale.

### Expected Behaviour

These creatures should be affected by scaling.

### Steps to reproduce the problem

1. Join any dungeon with summoned creatures (eg. Ragefire Chasm)

### AC rev. hash/commit

N/A

### Operating system

Windows

**Comment by kjack9** [comment]
Fixed in https://github.com/azerothcore/mod-autobalance/pull/133/commits/14eecd51a89dbe540c0ddf0af923c3c07ceedaaa
