### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by DykeRz** [azerothcore/mod-autobalance#147]
### Current Behaviour

Creatures attacking player after death and have 1 HP, so its dont die correctly

### Expected Behaviour

Creatures must die

### Steps to reproduce the problem

1. go to some instance
2. kill creatures
3. sometimes creatures dont die and attack you with 1 HP

### AC rev. hash/commit

[57e0b49](https://github.com/azerothcore/azerothcore-wotlk/commit/57e0b496bdc13441870f36963020271b6ae3f4fa)

### Operating system

debian 11

**Comment by DykeRz** [comment]
[https://ibb.co/qJ6td86](url)

**Comment by deef32** [comment]
Сonfirm

**Comment by DykeRz** [comment]
Princes don't die, doors don't open
![image (1)](https://github.com/azerothcore/mod-autobalance/assets/35741241/9d8133bf-eea7-4857-9b17-2d575cd6dd83)

**Comment by DykeRz** [comment]
Any fixes about it??

**Comment by kjack9** [comment]
Are you using the latest version of `mod-autobalance`? There have been some bugs with 1-HP creatures in the past but I think most of them have been fixed now. Do all creatures do this or only this one encounter?

Please also provide your entire `AutoBalance.conf` file, as well as any additional details as to how to make this happen again.

Closing as `invalid` for now, please re-open if you can provide the above requested information.
