### ISSUE TITLE
Bug:  Instant 80 after killing summoned creature/pet

### ISSUE THREAD

**Issue by duncrafter** [azerothcore/mod-autobalance#149]
### Current Behaviour

After killing a creature summoned by mobs or a mob pet, the player gains a huge amount of experience - enough to reach level 80 regardless of current level.

### Expected Behaviour

The player should gain the normal amount of experience as determined by the creature's level in relation to the player level and ExperienceModifier in creature_template.

### Steps to reproduce the problem

1. Kill a summoned creature/pet (eg. Razormane Wolf in Barrens or Voidwalkers in Durotar)
2. Observe

### AC rev. hash/commit

AzerothCore rev. bdba972ffc81 2023-08-01 19:13:49 +0000 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes or Modules

mod-ah-bot
mod-aoe-loot
mod-arac
mod-autobalance
mod-learn-spells
mod-solo-lfg
mod-transmog

**Comment by lewpar** [comment]
Can you share your config as well.

**Comment by duncrafter** [comment]
[AutoBalance.txt](https://github.com/azerothcore/mod-autobalance/files/12618532/AutoBalance.txt)

**Comment by kjack9** [comment]
I'm unable to replicate this. Do you also see this issue when `mod-autobalance` is the only mod enabled? What does `.ab mapstat` say when you're in the area? What about `.ab creaturestat` when you're targeting the Razormane Wolf?

![Razormane Wolf Kill](https://github.com/azerothcore/mod-autobalance/assets/19712078/e110b26d-a94a-4e52-96c6-8011739ce682)

![mapstat and creaturestat](https://github.com/azerothcore/mod-autobalance/assets/19712078/595664ac-c5e7-48a3-9176-62b171e8dd03)

**Comment by kjack9** [comment]
Marking as `invalid` for now, please re-open if you're able to reproduce this on the latest commit using only `mod-autobalance`.
