### ISSUE TITLE
(Crash) Icc  npc_icc_gauntlet

### ISSUE THREAD

**Issue by Fireevil** [azerothcore/mod-autobalance#159]
### Current Behaviour

https://gist.github.com/Fireevil/604253a9646655d6f9e07f8fe950708b

every time they reach the icc spider anuba trap after of sindragosa the server crashes

Before it didn't happen, the only changes I made was updating the server and adding the autobalance module

### Expected Behaviour

there should be no crash

### Steps to reproduce the problem

cross the room of spiders before sindragosa crashes when activating the trap

### AC rev. hash/commit

last rev b3bc89214776f29401f66e5e4fc4a38db2433295

### Operating system

windows 10

### Custom changes or Modules

mod-Autobalance last rev

**Comment by kjack9** [comment]
Funny story, but I can't figure out how to get to where you're talking about. Can you do a `.gps` and give me the X/Y/Z coordinates to the area with the issue?

Also, I looked through that crash dump you sent (thank you, by the way) and I don't see anything from AutoBalance in that crash stack. That being said, I'll test as well once I have the location and see if I see the same issue.

Thanks!

**Comment by Fireevil** [comment]
I'm just trying to make the crash appear but I can't get it, it seems that it is with more people, yesterday in 3 icc of 3 different raids when passing valithria dreamwalker and going down the elevator to the spider trap the server crashed

**Comment by Fireevil** [comment]
I don't know if this has anything to do with or affects the programming, the dragon appears with all her life with autobalance

**Comment by Fireevil** [comment]
![Screenshot_36](https://github.com/azerothcore/mod-autobalance/assets/88008285/c3df8e29-2271-4adb-adf1-1a457ce1704a)

**Comment by Fireevil** [comment]
There is also a problem with the second spell of the cannons in the ICC gunship battle, the charge bar does not go up when attacking the enemy ship with autobalance

**Comment by Fireevil** [comment]
oki thank you very much for your attention I do it right now

**Comment by kjack9** [comment]
Related to https://github.com/azerothcore/azerothcore-wotlk/issues/17575

**Comment by kjack9** [comment]
I can't replicate this, but I'm also by myself not in a large raid.

I don't see anything in the stack to indicate that there's an AutoBalance function call involved in this crash. I'd be very curious to know if you can replicate this without AutoBalance - I'm not opposed to the idea that AutoBalance is changing something that affects what the script does later. But without more information, I don't know how to continue to troubleshoot this.

I'll work on the other Valithria issue where her health is full - maybe that will affect this one?

**Comment by kjack9** [comment]
Closing. Please reopen if you can show that AB is involved in this crash somehow.
