### ISSUE TITLE
Bug: worldserver crash when a player create a character with wrong race and class

### ISSUE THREAD

**Issue by Vitumoc** [azerothcore/mod-autobalance#166]
### Current Behaviour

I use a latest version of AzerothCore, here is my server info:
AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/2217563fb1dc5143e3a9c386642f812dc2997465 2023-10-20 12:50:59 +0000 (master branch) (Unix, RelWithDebInfo, Static)

when a user use a modified client, and try to create a Orc Mage(Normally this is not possible), the worldserver will crash, an this is the end of the logfile.
![image](https://github.com/azerothcore/mod-autobalance/assets/31403302/5510da39-f610-4199-bc2a-fee6876b004c)

here is the crash log:
[<script src="https://gist.github.com/Vitumoc/8b3a21ad981bc1c6f6ca1cda64a8f11f.js"></script>](https://gist.github.com/Vitumoc/8b3a21ad981bc1c6f6ca1cda64a8f11f)

### Expected Behaviour

Character creation failed
user be kick out

### Steps to reproduce the problem

1. downlaod the patch
link：https://pan.baidu.com/s/1SR559ws1YtXxHnrGI3qUNw
code：l5kl

2. copy the path to client

3. login an create a orc mage

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/2217563fb1dc5143e3a9c386642f812dc2997465 2023-10-20 12:50:59 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 24. Characters in world: 22.
Connection peak: 33.
Server uptime: 1 day(s) 30 minute(s) 16 second(s)
Update time diff: 9ms, average: 8ms.
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 100612
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-87-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/vc/azeroth-data/maps. Total size: 291014951 bytes
vmaps directory located in /home/vc/azeroth-data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/vc/azeroth-data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_texts.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

List enable modules:

mod-autobalance
mod-eluna
mod-progression-system
mod-solo-lfg
mod-transmog

### Operating system

Ubuntu 22.04.2 LTS

**Comment by Fireevil** [comment]
t won't let me register on the page to download the patch, could you put the patch in a direct link to test?

**Comment by Vitumoc** [comment]
ok, here is a direct link

http://shayizhaocai.xyz:13055/patch-zhCN-Z.MPQ

**Comment by kjack9** [comment]
So you've modified the client to do something it's not supposed to, and now it crashes. As far as I know, you can't just create invalid characters on the client side and have the server be okay with that. None of your modules are handling non-standard characters.

Does this happen without AutoBalance enabled too? What is leading you to believe that AutoBalance specifically is causing this crash?

**Comment by Vitumoc** [comment]
Because we have discussed this problem in the azerothcore-wotlk issue before and tested it. When whithout the AutoBalance module , there will be no problem. When with the AutoBalance module, the problem will occur.

https://github.com/azerothcore/azerothcore-wotlk/issues/17577

**Comment by kjack9** [comment]
Got it, thank you for the link to the other issue - that is helpful.

I have no idea why an invalid class/race combination would specifically cause this - AutoBalance doesn't care at all about either of those things. I expect that something in AC handles it differently before it gets to me.

Let's try adding some checks for the function that crashed. Can you please try [this branch](https://github.com/kjack9/mod-autobalance/tree/kjack9/issue166) and let me know if that fixes the issue for you?

**Comment by Vitumoc** [comment]
Ok, I've tried this branch and got the same crash.

![image](https://github.com/azerothcore/mod-autobalance/assets/31403302/3dfeafa6-5cf2-47a4-86ca-335f45a735c0)

here is the crash log:

https://gist.github.com/Vitumoc/d1a248269f4c5e7b76607f0ea5d4fe25

Will this help us solve this problem? Is there anything else I need to do?

**Comment by kjack9** [comment]
It doesn't look like you're using my updated issue branch.

`0007FF676A6CA17  000000D1898FDC30  AutoBalance_PlayerScript::OnPlayerLeaveCombat+47  C:\Users\vc\Documents\ac\azerothcore\modules\mod-autobalance\src\AutoBalance.cpp line 3653`

Doesn't line up with

https://github.com/kjack9/mod-autobalance/blob/1c22e9b87e7c475cfeb0d35b01067471e08dad9a/src/AutoBalance.cpp#L3653

Can you try to download the issue branch from [this link](https://github.com/kjack9/mod-autobalance/archive/refs/heads/kjack9/issue166.zip) and compile again please?

**Comment by Vitumoc** [comment]
I'm trying the branch, but there is an error during compilation.


![image](https://github.com/azerothcore/mod-autobalance/assets/31403302/04c24fd3-0d19-4916-bdba-8fbb0ae605e3)


25>   Creating library C:/Users/vc/Documents/ac/build/src/server/apps/RelWithDebInfo/worldserver.lib and object C:/Users/vc/Documents/ac/build/src/server/apps/RelWithDebInfo/worldserver.exp
25>modules.lib(ModulesLoader.obj) : error LNK2019: unresolved external symbol "void __cdecl Addmod_autobalance_kjack9_issue166Scripts(void)" (?Addmod_autobalance_kjack9_issue166Scripts@@YAXXZ) referenced in function "void __cdecl AddModulesScripts(void)" (?AddModulesScripts@@YAXXZ)
25>C:\Users\vc\Documents\ac\build\bin\RelWithDebInfo\worldserver.exe : fatal error LNK1120: 1 unresolved externals
25>Done building project "worldserver.vcxproj" -- FAILED.
26>------ Rebuild All started: Project: ALL_BUILD, Configuration: RelWithDebInfo x64 ------
26>Building Custom Rule C:/Users/vc/Documents/ac/azerothcore/CMakeLists.txt
========== Rebuild All: 25 succeeded, 1 failed, 0 skipped ==========
========== Rebuild started at 9:23 and took 06:44.834 minutes ==========

**Comment by kjack9** [comment]
Rename the folder to `mod-autobalance`.

**Comment by Vitumoc** [comment]
thank you, I have tested this branch

here is the crash log:
https://gist.github.com/Vitumoc/d181445fd06bbb9072b1b3829b4beddc

**Comment by kjack9** [comment]
Thanks, that helps.

I think I've done all the checking I can before I make that `GetMap()` call. I made sure the player exists and then called a function that player. The function that's actually failing is inside `GetMap()`, so I don't think I can fix this from AutoBalance.

Let me leave some findings over on the other bug and see if anyone is able to help there. I am... 85% sure this is a bug with Azerothcore, not AutoBalance.

**Comment by kjack9** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/17577#issuecomment-1786725790
