### ISSUE TITLE
Bug: Hydross the Unstable, Shade of Aran summoned creatures not scaling down

### ISSUE THREAD

**Issue by alca-00** [azerothcore/mod-autobalance#168]
### Current Behaviour

Hydross the Unstable (Creature ID 21216) summons the following:
Pure Spawn of Hydross (22035)
Tainted Spawn of Hydross (22036)

Identical stats for both creatures, using these stats for reference:
https://wowgaming.altervista.org/aowow/?npc=22035
Level: 71
Health: 30,160
Armor: 7,018
Melee: 1,925 - 2,723 (Frost)

The Hydross summons appear with their level set to 73, health is around 30k indicating that it hasn't been scaled down. When using .ab creaturestat it mistakenly returns the intended scaled-down stats however.

My Settings:
AutoBalance.LevelScaling=0 (summoned creatures should be level 71 but something's scaling them up?)
![ssc mapstat](https://github.com/azerothcore/mod-autobalance/assets/149727824/2ad37fec-f904-4c42-bb49-4f91f051a440)
Hydross Spawns when they appear in battle:
![Hydross Spawns](https://github.com/azerothcore/mod-autobalance/assets/149727824/cc8147d2-9a67-46e6-a544-01b59970985b)
For reference a pic of Hydross himself which as far as I can tell is scaling correctly
![Hydross Stats Scaled Down](https://github.com/azerothcore/mod-autobalance/assets/149727824/aeea0c0e-426c-495d-85cf-e0a7cf5773a8)

When I use .ab setoffset I can set the spawns down to their intended HP (which should be around 3k) but they remain level 73.
Unsure about the accuracy of the Armor & Damage scaling but they might need to be looked at also.

Shade of Aran:
Also summons creatures: 
Conjured Elemental (17167)
They appear with 10k hp indicating that not everything is scaling down either. They are meant to be level 73 so no changes there.
Karazhan mapstat for reference
![kara mapstat](https://github.com/azerothcore/mod-autobalance/assets/149727824/0166ea6a-e67b-44fb-a811-8319d605c713)

### Expected Behaviour

Summoned creature stats should automatically scale down to the intended AB settings.
Summoned creature should not scale its levels if LevelScaling=0

### Steps to reproduce the problem

Hydross The Unstable:
.tele ssc
Begin Hydross encounter
Cross the midway point of the battle area to trigger his Tainted Spawn of Hydross summons
Cross back again to summon Pure Spawn of Hydross

Shade of Aran:
.tele kara
Begin Shade of Aran encounter
Bring boss HP down until he summons Conjured Elementals

### AC rev. hash/commit

AzerothCore rev. fb83c22dd292+ 2023-11-02 12:30:03 -0300 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

**Comment by kjack9** [comment]
I have uploaded what I believe is a fix for this issue. Please try this version:

https://github.com/kjack9/mod-autobalance/archive/refs/heads/kjack9/issue169.zip

Note that you will need to rename the folder to `mod-autobalance` in order to test.

Let me know if this fixes the issue you're having.

**Comment by alca-00** [comment]
Both Hydross & Shade of Aran summons scale down as intended. Brilliant! Will check out some more instances while I'm at it

**Comment by alca-00** [comment]
I've noticed that Tainted Spawn of Hydross are summoned as level 73. Their creature template says their min/max level range is 71. In BWL's Nefarian encounter he summons a variety of Drakonid npcs that have a min/max of 60 but appear as level 63 for me. 

Is this intended? My level scaling turned off so I'm assuming these creatures are automatically setting themselves to the same level as the boss they're tied to.

**Comment by kjack9** [comment]
> I've noticed that Tainted Spawn of Hydross are summoned as level 73. Their creature template says their min/max level range is 71. In BWL's Nefarian encounter he summons a variety of Drakonid npcs that have a min/max of 60 but appear as level 63 for me.
> 
> Is this intended? My level scaling turned off so I'm assuming these creatures are automatically setting themselves to the same level as the boss they're tied to.

Pop a new issue for this one, I can check it out. I _believe_ that AzerothCore is the one mandating that the summon it the same level as the summoner, but I can definitely confirm and see if there's something that needs to be updated in AutoBalance or the AC Core.

**Comment by alca-00** [comment]
> > I've noticed that Tainted Spawn of Hydross are summoned as level 73. Their creature template says their min/max level range is 71. In BWL's Nefarian encounter he summons a variety of Drakonid npcs that have a min/max of 60 but appear as level 63 for me.
> > Is this intended? My level scaling turned off so I'm assuming these creatures are automatically setting themselves to the same level as the boss they're tied to.
> 
> Pop a new issue for this one, I can check it out. I _believe_ that AzerothCore is the one mandating that the summon it the same level as the summoner, but I can definitely confirm and see if there's something that needs to be updated in AutoBalance or the AC Core.

I think you're right, I'm looking at summoned creatures in non-instanced zones which are entirely unaffected by autobalance and they scale to their summoner's level.
Balgaras the Foul (ID 1364) summons Voidwalker Minion (8996) with a level range of 42-56 in the creature template and it appears as a level 31 for example.

**Comment by kjack9** [comment]
> > > I've noticed that Tainted Spawn of Hydross are summoned as level 73. Their creature template says their min/max level range is 71. In BWL's Nefarian encounter he summons a variety of Drakonid npcs that have a min/max of 60 but appear as level 63 for me.
> > > Is this intended? My level scaling turned off so I'm assuming these creatures are automatically setting themselves to the same level as the boss they're tied to.
> > 
> > 
> > Pop a new issue for this one, I can check it out. I _believe_ that AzerothCore is the one mandating that the summon it the same level as the summoner, but I can definitely confirm and see if there's something that needs to be updated in AutoBalance or the AC Core.
> 
> I think you're right, I'm looking at summoned creatures in non-instanced zones which are entirely unaffected by autobalance and they scale to their summoner's level. Balgaras the Foul (ID 1364) summons Voidwalker Minion (8996) with a level range of 42-56 in the creature template and it appears as a level 31 for example.

Hey, my old friend VoidWalker Minion! That's the creature I dug into to understand what was going on with AC and levels for summons. Another example is Shaman totems - they're creatures! And they have a level range of 1-80. Which is bad when your level 60 shaman drops a level 3 totem in Scholomance and pulls the entire instance. Not that I'd know about that.

I think this is mostly a side effect of less-than-perfect implementation of scaling for summons on the AC side. I'll still take a look at make sure I'm not accidentally causing this.

**Comment by kjack9** [comment]
I made one more change to reduce the amount of stat generation runs get called when an instance is created. Can you please re-test and make sure this still fixes the issue?

https://github.com/kjack9/mod-autobalance/archive/refs/heads/kjack9/issue169.zip

**Comment by alca-00** [comment]
Unfortunately it does not fix summons like the original. Both the Hydross & Aran summons appear to back to an unscaled health pool upon being summoned. Manually reloading or changing autobalance offsets scales them back down to the proper values.

**Comment by kjack9** [comment]
Okay, I blame me pushing that update out when I was way too tired to be doing so. I have actually checked all the bug report examples now and I think everything is fixed. Something in AC is altering the max health of the creature after I change it but before its added to the world. I now check for this and fix the max health if needed.

Try this one more time:
https://github.com/kjack9/mod-autobalance/archive/refs/heads/kjack9/issue169.zip

Tip: if you need a previous version from that branch, you can view the commits here:
https://github.com/kjack9/mod-autobalance/commits/kjack9/issue169

**Comment by alca-00** [comment]
Yup, summons automatically scale for both bosses now.
