### ISSUE TITLE
Bug: Vaelastrasz the Corrupt appears with 100% health

### ISSUE THREAD

**Issue by alca-00** [azerothcore/mod-autobalance#170]
### Current Behaviour

![BWL Vael](https://github.com/azerothcore/mod-autobalance/assets/149727824/fe884bd0-e30d-4fc8-b84a-5a613cac98cf)

Possibly similar to #164
Vaelastrasz is scaled down but appears at full health. Beginning the encounter & resetting it fixes him and places him at the intended 30% HP.

### Expected Behaviour

Vaelastrasz the Corrupt should spawn with 30% health before the boss encounter begins. 

### Steps to reproduce the problem

.tele bwl
/tar vael
Check the boss health

### AC rev. hash/commit

AzerothCore rev. fb83c22dd292+ 2023-11-02 12:30:03 -0300 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

**Comment by kjack9** [comment]
Looks like there may be a timing issue here. Vael's [`Reset()`](https://github.com/azerothcore/azerothcore-wotlk/blob/68263b773daa1b035086c86ca7c4617b62d4382e/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_vaelastrasz.cpp#L101) function sets the health to 30%, but it doesn't appear to happen before I change the health value. I will investigate.

![image](https://github.com/azerothcore/mod-autobalance/assets/19712078/ecbdc7c8-88c7-4437-b851-308ab026dcc7)

**Comment by kjack9** [comment]
Valithria Dreamwalker is actually working fine - starts at scaled 50% as intended. So I'll figure out what's different between them.

**Comment by kjack9** [comment]
The latest push should fix this one too - my hacky fix for the other issue was causing this one.

https://github.com/kjack9/mod-autobalance/archive/refs/heads/kjack9/issue169.zip

Can you please test?

**Comment by alca-00** [comment]
It works, Vaelastrasz has his health properly set to 30%! Entered a fresh BWL instance normally through UBRS and by using teleports, each time unbinding the instance to be sure. 

Vael's HP is automatically set to 30%. Started the encounter and reset it, HP returns back to 30% as well. Seems good

**Comment by kjack9** [comment]
Try this one more time:
https://github.com/kjack9/mod-autobalance/archive/refs/heads/kjack9/issue169.zip

Tip: if you need a previous version from that branch, you can view the commits here:
https://github.com/kjack9/mod-autobalance/commits/kjack9/issue169
