### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by joshjoshajosh** [azerothcore/mod-autobalance#193]
### Current Behaviour

When I have this folder in: ..\Core\modules\mod-autobalance
The build fails with hundreds of "LocaleConstant" errors and
Cannot open input file '..\..\modules\RelWithDebInfo\modules.lib'

### Expected Behaviour

No errors during Project Build

### Steps to reproduce the problem

Copy mod-autobalance into modules folder, cmake, clean, build.

### AC rev. hash/commit

Unable to build to find out, builds fine without mod

### Operating system

Win 10

**Comment by Nyeriah** [comment]
Clone instead of downloading the zip file

**Comment by joshjoshajosh** [comment]
What's the difference?

**Comment by Nyeriah** [comment]
> What's the difference?

The zip folder dates from September 26 when the fix you need to compile it was commited October 27

**Comment by joshjoshajosh** [comment]
Oh because I was downloading the "Stable" version.....shouldn't that be changed if it's not stable?

**Comment by Nyeriah** [comment]
> Oh because I was downloading the "Stable" version.....shouldn't that be changed if it's not stable?

Sure, I've removed the broken zip
