### ISSUE TITLE
Possible to set this for BC raids only?

### ISSUE THREAD

**Issue by andoys** [azerothcore/mod-autobalance#25]
Possible to set this for BC raids only?
Including the rewards ( It also doesn't state in the config how many tokens they get? is it 1 per boss?)

**Comment by Yehonal** [comment]
Currently it's not possible from config for both of issues you requested, but there are 2 solutions:

- with this hook you can create a script where insert an if that returns false if a player/party is in a specific instance (All Wotlk instance) https://github.com/azerothcore/mod-vas-autobalance/blob/master/src/VASAutoBalance.h#L13

- in same script you can implement this hook:
https://github.com/azerothcore/mod-vas-autobalance/blob/master/src/VASAutoBalance.cpp#L812
That is the same we used to implement the reward system with same conditions

**Comment by andoys** [comment]
Thank you for the reply. since i am not good with coding. I have to study this first

**Comment by Yehonal** [comment]
I'm going to create a PR that will allow to do it without any particular experience in coding. I'll keep you posted

**Comment by pangolp** [comment]
From what they told me, this issue has already been resolved and this is no longer valid. I think it could be closed.
