### ISSUE TITLE
del

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/mod-autobalance#28]
del

**Comment by Mitradis** [comment]
AutoBalance.DisabledID not work

**Comment by Viste** [comment]
AutoBalance.DisabledID - don't handle in code, only force

**Comment by Mitradis** [comment]
it is supported just there is a little logic wrong (did not think over this point).

FIX: in file AutoBalance.cpp

int GetForcedCreatureId(int creatureId)
{
    if (forcedCreatureIds.find(creatureId) == forcedCreatureIds.end()) // Don't want the forcedCreatureIds map to blowup to a massive empty array
    {
        return -1;
    }
    return forcedCreatureIds[creatureId];
}


up this block to CreatureTemplate const *creatureTemplate = creature->GetCreatureTemplate();

        uint32 maxNumberOfPlayers = ((InstanceMap*)sMapMgr->FindMap(creature->GetMapId(), creature->GetInstanceId()))->GetMaxPlayers();
        //    SOLO  - By MobID
        if (GetForcedCreatureId(creatureTemplate->Entry) >= 0)
        {
            maxNumberOfPlayers = GetForcedCreatureId(creatureTemplate->Entry); // Force maxNumberOfPlayers to be changed to match the Configuration entry.
			if (maxNumberOfPlayers == 0)
			{
				return;
			}
        }

**Comment by Mitradis** [comment]
for Alterac:
```
		uint32 mapId = creature->GetMapId();
		if (mapId == 30)
			return;
```

**Comment by Yehonal** [comment]
Can someone confirm it?
