### ISSUE TITLE
Possibility to scale overworld creatures with a different configuration?

### ISSUE THREAD

**Issue by Artanisx** [azerothcore/mod-autobalance#31]
Hello,
thank you for your great mod :-)

Since I (will soon) play with a friend of mine, I was wondering if there was the possibility to scale the overworld creatures (the quest mobs in the world basically) with a different configuration, namely to make them stronger to be more of a match for two players playing togheter. 

It's the opposite of what the mod does in dungeons (scaling them to become weaker so that 2 players can take them), and would make both the levelling experience and the dungeon/raid experience doable in any number of players and with a good challenge.

Is this possible?

Thank you!!

**Comment by Yehonal** [comment]
You can configure autobalance mod even for world creatures with the correct
configurations, but it's quite hard to configure everything in the right
way.
With autobalance sysyem i've simulated a "mythic" sysyem with unlimited
levels for both outworld and instance creatures,but you must use also code
(there are 2 hooks that can be used for this scope).
Before doing so i suggest you to try a simple x2 rate in creature melee
damages and spell damage in the worldserver.conf file, you can set it for
different kind of creature so you can exclude bosses and rare elite
eventually

Let me know

**Comment by Artanisx** [comment]
Hi Yehonal, 
thank you for taking your time to reply to me. I'm still quite new to AzerothCore, would you be able to point me to the right configuration? I think doubling melee damage/spell damage only for non-dungeon/raid creatures might do the trick!

Would it be (for doubling):
`Rate.Creature.Normal.Damage          = 2`
and
`Rate.Creature.Normal.SpellDamage          = 2`

And keeping the AutoBalance settings as they are (only active on Dungeon and Raids)?

P.S. I would like to know more of your "mythic system", it sounds interesting :-)

Thanks!

**Comment by Yehonal** [comment]
You're welcome :)

Yes, you can use such configurations, however, you can try to double all
kind of creatures (normal, elite and rare elite at least) and configure the
autobalance with lower rates. It should do the trick.
Let me know if it works for you.

**Comment by BarbzYHOOL** [comment]
good trick
