### ISSUE TITLE
build warning unsafe use of type bool

### ISSUE THREAD

**Issue by milestorme** [azerothcore/mod-autobalance#32]
windows build warning x64
`13>C:\azerothcore-wotlk\modules\mod-autobalance\src\AutoBalance.cpp(299): warning C4804: '<': unsafe use of type 'bool' in operation
13>C:\azerothcore-wotlk\modules\mod-autobalance\src\AutoBalance.cpp(353): warning C4804: '>': unsafe use of type 'bool' in operation
13>C:\azerothcore-wotlk\modules\mod-autobalance\src\AutoBalance.cpp(393): warning C4804: '>': unsafe use of type 'bool' in operation`

**Comment by BarbzYHOOL** [comment]
There is a comparison of a bool

example:

PlayerChangeNotify < 0

But does that make any sense to compare a bool ? it's either 0 or 1, that's probably these errors

**Comment by kjack9** [comment]
This is a very old issue that no longer appears to be applicable.
