### ISSUE TITLE
Possible to scale dungeons differently to raids?

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/mod-autobalance#33]
Hi,

Is it possible to have an option in this where dunegons are scaled differently to raids?

Many thanks!

**Comment by BarbzYHOOL** [comment]
explain more, can you give an example of the config options for example? (it's for potential developers :P)

**Comment by Yehonal** [comment]
The current formula is perfectly balanced for both dungeons and raids. I
wrote the formula here:
https://github.com/azerothcore/mod-autobalance/issues/4#issuecomment-370183764

I suggest to use code in this case, you can use one of these hooks
https://github.com/azerothcore/mod-autobalance/blob/master/src/AutoBalance.h#L15

However, would be nice to have a specific hook to change configuration
values based on specific conditions

**Comment by pangolp** [comment]
From what they told me, this issue has already been resolved and this is no longer valid. I think it could be closed.

**Comment by Helias** [comment]
then let's close it, if anyone encounter this issue he can re-open it
