### ISSUE TITLE
AutoBalance.numPlayer vs AutoBalance.XPlayer?? I don't understand this option

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-autobalance#34]
What the hell does this mean:

```
#     AutoBalance.numPlayer
#        Set Server to level of solo mode.
#        Set to 0 to Disable -SOLO Mod.
#        Example: .AutoBalance.XPlayer = 1 will set everything for a 1 player game.
#        Default:     1

AutoBalance.numPlayer=1.0
```

I really don't understand. In top of that, the example is talking about AutoBalance.XPlayer????????? wtf

So what does this do? if you set it to 1.0 it's for 1.0 player ? 
Or maybe, it's only when a solo player enters a dungeon, then what is the modifier for?

**Comment by Yehonal** [comment]
https://github.com/azerothcore/mod-autobalance/commit/e5c63454b3f8f5159ae1d7584915c9bfa30830c1

**Comment by BarbzYHOOL** [comment]
ah ok it's unused
