### ISSUE TITLE
List of not working options

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-autobalance#44]
1) - [x] AutoBalance.levelScaling

```
#
#     AutoBalance.levelScaling
#        Check the max level of players in map and scale creature based on it
#        0 = Disabled
#        1 = Enabled only in dungeons
#        2 = Always enabled
#        Default:     1

AutoBalance.levelScaling=2

```
If you set to 2, it's like it's set to 0.

EDIT: WRONG, it works fine I think, just need to make sure you're not in the offset level range

2) - [ ]  AutoBalance.numPlayer

This option has been removed, but some of the code is still present 

PS: will add more when i test the other options

**Comment by Stoabrogga** [comment]
- **numPlayer** is removed here: #41 
- **levelScaling** is treated like a boolean in the code, so everything other than 0 means "true". The description in the config file has to be changed accordingly.

**Comment by Yehonal** [comment]
about level scaling: https://github.com/azerothcore/mod-autobalance/pull/43#discussion_r382471003

**Comment by pangolp** [comment]
From what they told me, this issue has already been resolved and this is no longer valid. I think it could be closed.
