### ISSUE TITLE
Option rate.damage vs MinDamageModifier

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-autobalance#45]
AutoBalance.rate.damage = 1.0

vs

AutoBalance.MinDamageModifier=0.01

What's the difference between these two options?

**Comment by Darkon47** [comment]
I'm not sure, but a quick glance to me says that the first one is a multiplier on how much the damage gets adjusted, and the latter is a minimum amount the damage can be reduced relative to its base damage.

**Comment by BarbzYHOOL** [comment]
yes exactly, so it means if the balancing gives you too small dmg, then increase this (probably useful only for ragefire and such?)
