### ISSUE TITLE
AutoBalance.levelUseDbValuesWhenExists = 1  

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-autobalance#46]
By default, it's set to 0

I set it to 1 and it increased the HP of the mobs

Conclusion: I think this setting is quite good for a more blizzlike approach because when your level matches the dungeon, then it will scale according to the DB values and the result is probably harder than expected, which seems appropriate for a dungeon of your level, what do you think guys?l

**Comment by kjack9** [comment]
Closing this (very old) issue since the setting in question doesn't exist anymore.
