### ISSUE TITLE
Allow to tune Bosses differently from packs of mobs

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-autobalance#47]
I tried low level dungeons like wailing caverns and blackrock depths and the packs of mobs are way deadlier than the bosses (example: a pack of 6 mobs can have 4 times more HP in total than a boss)

If I tune down the packs of mobs for solo play, the bosses are way too easy.

If we could tune the bosses differently than the mobs, it would be really interesting, notably the flat parameter to change the damage, armor, mana and most notably health.

But we need to take note that the bosses seem like they aren't correctly defined in the DB (some do too few damage), so if we ever change them in AC world database, then it might affect this issue and its related fix.

**Comment by Stoabrogga** [comment]
You can already do this using these options:
- ForcedID40 (scale creatures in the list to 40 players)
- ForcedID25 (scale creatures in the list to 25 players)
- ForcedID10 (scale creatures in the list to 10 players)
- ForcedID5 (scale creatures in the list to 5 players)
- ForcedID2 (scale creatures in the list to 2 players)
- DisabledID (don't scale the creatures in the list, can only be used after #42 is merged)

I think bosses can be identified by type flag "CREATURE_TYPEFLAGS_BOSS":
http://www.azerothcore.org/wiki/creature_template#type_flags
But I don't know if it is really a good idea to implement a new option affecting all bosses. Perhaps a kind of "boss multiplier" which is added to the calculation.

**Comment by BarbzYHOOL** [comment]
no i can't use this option "forcedID" to put all the low level dungeons bosses one by one

also i'm not even sure what this feature does, you mean i could force a boss to be a 5man boss, but then if you enter the zone with 2 players or in solo it doesn't make much sense

**Comment by Darkon47** [comment]
I will submit a PR doing this when i get home next week. this is too much to code from my phone.

**Comment by BarbzYHOOL** [comment]
note: there is a big difference between low level dugneons and high level dungeons (as expected), probably handled by the parameter AutoBalance.LevelEndGameBoost = 1

**Comment by BarbzYHOOL** [comment]
selecting all bosses with the type_flags:

```
SELECT name, subname, minlevel, rank
FROM `creature_template`
WHERE type_flags = type_flags | 4
```

result is completely wrong haha, so not a solution
