### ISSUE TITLE
Spells not scaling?

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-autobalance#48]
Fighting Bael'gar in blackrock depths, anytime he casts his spell 13880 it stacks up, and i don't think it scales to the level or to the number of players.

I dont think anything can be done though because spells are static in the dbc

**Comment by Yehonal** [comment]
This one? https://wowgaming.altervista.org/aowow/?spell=13880

**Comment by BarbzYHOOL** [comment]
Yes, when i tried as a level 16  SOLO player in BRD (which is lvl 52+), it did same damage and armor reduction (unless I made a mistake). I remember clearly taking 150 damage from the spell and at level 16 that's 40% of my HP.

When I tried as a level 53 SOLO player, it did similar damage.

**Comment by Yehonal** [comment]
On autobalance we're using ModifyPeriodicDamageAurasTick to modify the damage from periodic auras like that

can you check again? how many stacks did you have? can you check the armor reduction on level 16 etc?

**Comment by BarbzYHOOL** [comment]
ok I just retried and in fact the tooltip says some values but the real values are different so that seems to work, same for the summoned NPCs
This spell is also scaled https://wowgaming.altervista.org/aowow/?spell=13895

Everything fine, wrong issue

PS: offtopic but if you could add a file to the modules like a "manifest.json" or something like that where we can put (optionally) a core commit and if the core is not matching this core commit, then it warns the user that the module will be bugged (because I had forgotten to take the commit for the core hook for example). Could also add a variable for the module versioning. And also a "dependencies" array when a module depends on another module (more complex but i remember you started working on this)

**Comment by Yehonal** [comment]
Yes, we need something like that
