### ISSUE TITLE
Conf to prevent scaling when player is above X levels of the desired dungeon

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-autobalance#49]
Actually, we can prevent level scaling for players with a higher level than the dungeon.
However, if you enter a very low dungeon with a high level character, the dungeon will still scale as if you were in the required level range.

There should be a conf option to prevent this

Autobalance.DisableBalancingForCharHigherLevelThan = 10 (means if you are lvl 35, you go to Wailing Caverns, then there is no autobalancing, but you are level 25, there is autobalancing)

Set to 0 to disable.

The name doesn't sound good but it's self explanatory.

Also it should announce "dungeon set to its original content" or something like that

**Comment by Yehonal** [comment]
https://github.com/azerothcore/mod-autobalance/blob/master/conf/AutoBalance.conf.dist#L63

**Comment by BarbzYHOOL** [comment]
no, it doesn't work like that, read my post again first line :P

here are my settings:

```
AutoBalance.levelHigherOffset = 3
AutoBalance.levelLowerOffset  = 80
```

**Comment by kjack9** [comment]
This was reworked in #125 and later commits.
