### ISSUE TITLE
Edwin van cleef had less HPs than his summoned units

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-autobalance#53]
Bug or not bug?

**Comment by BarbzYHOOL** [comment]
yes it's a bug @yehonal

he summons the same exact mobs as the one next to him, so the guards near him have 461 hp, but the summoned mobs (same mobs) have 1400 HP

**Comment by BarbzYHOOL** [comment]
yeah, if disabled autobalance, they have 1400 hp, so all summoned units are probably BUGGED

**Comment by Grimfeather** [comment]
The issue I encountered is related to this, so I'll post it here.

In SFK Wolf Master Nandos summons a Lupine Horror (entry 3863)
This summon is not scaled down by autobalance

**Comment by kjack9** [comment]
This should be resolved in more-recent versions of `mod-autobalance` - I now look at the creature that summoned the unit and have their modifiers/level match their summoner. If this is still happening in the latest revisions, please re-open this issue.
