### ISSUE TITLE
compile warning

### ISSUE THREAD

**Issue by humanana** [azerothcore/mod-autobalance#55]
AzerothCore revision            : 59e00ad1245d 2020-03-01

![warn](https://user-images.githubusercontent.com/51247678/75680896-1642a300-5cc5-11ea-9feb-b32a20ddafee.JPG)

**Comment by BarbzYHOOL** [comment]
@humanana test this PR plz https://github.com/azerothcore/mod-autobalance/pull/52 and give feedback on it

**Comment by humanana** [comment]
> @humanana test this PR plz #52 and give feedback on it

isn't it the same commit on this zip ?

![auba](https://user-images.githubusercontent.com/51247678/75720296-d00f3300-5d08-11ea-97a4-e45036718680.JPG)
![auba2](https://user-images.githubusercontent.com/51247678/75720298-d1d8f680-5d08-11ea-9d0d-e53498127cd5.JPG)

**Comment by BarbzYHOOL** [comment]
no, be more curious and check the commits in the PR listed

also read our wiki on how to test a Pull Request (but apply this to the module repository, not the core repository) !!!

**Comment by humanana** [comment]
Am I on the right one right now? if so it still happen the warning when compiling > <

by meaning (but apply this to the module repository, not the core repository) !!! 
       I did put the autobalance in the module of azerothcore folder, right ?

![auto5](https://user-images.githubusercontent.com/51247678/75725196-875c7780-5d12-11ea-89af-18b4a252b273.JPG)


![auto4](https://user-images.githubusercontent.com/51247678/75724840-cccc7500-5d11-11ea-9c84-03bb6c11a52c.JPG)

![auto3](https://user-images.githubusercontent.com/51247678/75724771-a73f6b80-5d11-11ea-8a18-3d6c774826d6.JPG)

**Comment by BarbzYHOOL** [comment]
Please, make an effort, the commit hash is exactly the same 180cc0... so you didn't use the right commit.

Follow this for mod-autobalance and use GIT for that http://www.azerothcore.org/wiki/How-to-test-a-PR experiment with git, you will thank me later for that

**And you can't do it by downloading the zip archive.**

**Comment by humanana** [comment]
ohh I'm sorry and thank you for the link and guiding tips

 I'll try out again > <

**Comment by BarbzYHOOL** [comment]
basically you git clone mod-autobalance

then 

```
git checkout -b pr-fix

git pull origin pull/52/head
```

you recompile, you test, if it works you `git checkout master` and then I merge it and then you `git pull`

Well I understand it's very complex for a beginner, but you should really try to understand all of this to be able to work/test efficiently

**Comment by humanana** [comment]
I try git pull PR 52 now and recompile again

it now show no warning but haven't test in gameplay but it should be fine right?

![auto6](https://user-images.githubusercontent.com/51247678/75757656-58bbbc80-5d65-11ea-9e62-9c8b220ac395.JPG)

**Comment by BarbzYHOOL** [comment]
exactly, can you test in game (quickly) to make sure it's working? then I merge it and then I tell you how to proceed to go back to master branch :)

**Comment by humanana** [comment]
should be working fine I think only test on stockade I'm warrior lv 27 also the mob scale to lv 27 as well as max health > <'

![auto7](https://user-images.githubusercontent.com/51247678/75823355-2f864500-5dd4-11ea-8fec-f8afe1314081.JPG)

![auto8](https://user-images.githubusercontent.com/51247678/75823370-3614bc80-5dd4-11ea-9c11-a5afd2a31a91.JPG)

normal mob in stockade max health should be around 1800-2200

![auto9](https://user-images.githubusercontent.com/51247678/75823506-7411e080-5dd4-11ea-8638-8c0619347023.JPG)

**Comment by BarbzYHOOL** [comment]
So I merged it, so now you can go into your module repository with git, you do this:

```
## LIST THE BRANCHES
git branch -vv
## GO BACK TO MASTER BRANCH
git checkout master 
## PULL THE LATEST COMMITS
git pull
## DELETE THE TESTING BRANCH
git branch -D pr-fix
## LIST THE BRANCHES
git branch -vv
```
That's it :) 

Thank you, do not hesitate to test other PRs now you know how to proceed :P

**Comment by humanana** [comment]
thx again for guiding and help >v<
