### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-autobalance#56]
I can't use github right now, it's completely bugged so i write a todo list:

README:
- Add some easy testing macros examples
- Explain that we can reload the conf and not reboot for testing config options
- "Set AutoBalance.playerCountDifficultyOffset = 4 to simulate a 5 man group"

CONF:
- Improve description of mindamagemodifier
- Explain that the flat rates (Autobalance.rate...) are only applied when autobalance is activated == when there are less players than the dungeon size
- Explain that `rate.damage` TAKES into account changes from the worldserver.conf `Rate.Creature.Elite.Elite.Damage`, same for `Rate.Creature.Elite.Elite.HP` so it's a rate added on top of all the others

**Comment by kjack9** [comment]
This is a legacy todo list that is not applicable to the latest versions of `mod-autobalance`.
