### ISSUE TITLE
Exclude group size achievements from triggering + disable balancing per group IG

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-autobalance#59]
Autobalance needs a conf option to exclude achievements from being earned when the balancing is activated, example: https://db.frostgram.eu/?achievement=578

But it would also require a way for the players to disable autobalancing if they want to earn that specific achievement (because else, they would automatically trigger it and so the achievement would never be attainable). There could also be a bonus reward for players deciding to stick to a full group (== extra gold?)

**Comment by kjack9** [comment]
This is out of scope for now - currently, AutoBalance settings apply to all copies of an instance regardless of what the player wants for difficulty. That may change in the future, but this request isn't possible with the way AutoBalance is currently setup.

**Comment by kjack9** [comment]
Not planned.
