### ISSUE TITLE
Armor value problem

### ISSUE THREAD

**Issue by aleigood** [azerothcore/mod-autobalance#60]
AutoBalance.levelScaling = 0
AutoBalance.rate.global = 3.0
AutoBalance.rate.health = 1.0
AutoBalance.rate.mana   = 1.0
AutoBalance.rate.armor  = 1.0
AutoBalance.rate.damage = 1.0

The actual armor value of creatures in the game is 3:

Instance player Count: 1
Selected level: 70
Damage multiplier: 0.357609
Health multiplier: 0.357609
Mana multiplier: 0.357609
Armor multiplier: 3.000000

**Comment by BarbzYHOOL** [comment]
this is incomprehensible

**Comment by aleigood** [comment]
Line 719:
```
creatureABInfo->ArmorMultiplier = globalRate * armorMultiplier;
```
should be:
```
creatureABInfo->ArmorMultiplier = defaultMultiplier * globalRate * armorMultiplier;
```

**Comment by BarbzYHOOL** [comment]
hey you're probably right, have you tried ingame?

You can make the pull request easily by clicking this link, editing the file and then submitting the PR https://github.com/azerothcore/mod-autobalance/blob/master/src/AutoBalance.cpp#L719

**Comment by aleigood** [comment]
It has been tested and can now be calculated correctly.

**Comment by steenburgh** [comment]
What effect was this having on players? I'm trying to decide if it's worth updating my plugin just to pull in this change. If I understand correctly, it looks like this was preventing armor from being scaled properly, and instead always scaling it to 100%. Is that correct?
