### ISSUE TITLE
Vanilla Dungeons with a player limit > 5 (like LBRS or UBRS) scale issues

### ISSUE THREAD

**Issue by Artanisx** [azerothcore/mod-autobalance#67]
Hello!
First things first: Loving this mod. I've played all of Vanilla from 1 to 60 with a friend and thanks to this mod we could basically have everything to scale for two players.

However, now that we reached the Vanilla endgame (we locked the experience gain, so we can stay level 60), we've ran into some scaling issues. While 5 player dungeons like Dire Maul work very well as usual, the dungeons with a higher than 5 player limit (like LBRS or UBRS) seems to scale wrongly, making the mobs have too few HP and do too few damage.
LBRS for instance, had mobs with very few HP that we could essentially AoE down without any problem at all.

I think this is because the player max count for these dungeons is 15 and as such it scales them down too much than it should.

For example (numbers are just to explain), while for 5 player dungeons it would do 5 / number of players (in our case 5/2 = 2.5 scaling), since LBRS/UBRS has 15 player limit, I think it does 15 / number of players (in our case 15/2 = 7.5 scaling) basically scaling them too low since in reality these dungeons were still designed to be beaten by a 5 player group (specially post TBC release).

Is there  any setting we could use to avoid this happening or does this require some update on the code?

Thanks :)

**Comment by kjack9** [comment]
I think this should be covered by the settings created in #125 and later commits. You can always adjust the scaling values for LBRS/UBRS specifically to your taste, although I admit it is tough to find a single setting that works well for both sets of instances. Regardless, you should have the tools to handle this now.
