### ISSUE TITLE
 Additional option ( if it remains possible)

### ISSUE THREAD

**Issue by ludaxt** [azerothcore/mod-autobalance#68]
Hello,

set up a condition for the number of players to activate the autobalance example: raid 25 = 10/15 players minimum to activate the scalling.
Currently the scalling is activated with only 2 players which makes the raid too easy for my taste
very good module for the server not very people

**Comment by kjack9** [comment]
This will be closed by https://github.com/azerothcore/mod-autobalance/pull/155, which adds exactly the setting you're describing - setting a minimum player number that scaling will not go below.
