### ISSUE TITLE
autobalance_NbrMinPlayer

### ISSUE THREAD

**Issue by zarroc2017** [azerothcore/mod-autobalance#69]
with this mod : autobalance (https://github.com/Ramys/mod-vas-autobalance). I want to know if it's possible to create a number of player minimum for activated the boss's scaling in ice crown citadelle (ICC)  raid with 25 players (heroic or not)?

exemple i want minimum 15 player in ICC for activate the scaling, if number of player <15 then the scaling is not activate 

thank for your work and i hope see you soon

**Comment by kjack9** [comment]
This will be closed by #155, which adds exactly the setting you're describing - setting a minimum player number that scaling will not go below.
