### ISSUE TITLE
damage calculation or creature scaling issue?

### ISSUE THREAD

**Issue by pagimu** [azerothcore/mod-autobalance#71]
Hi everybody,
I have a problem with the "damage calculation/creature scaling" for rogue. In dungeons the rogue gets too little damage and deals too much. Autobalance is used on the server. I know the problem is related to autobalance module. But I don't know why. All other classes works fine. 

As example, If I go to Ragefire Chasm as a lvl 25 rogue the creature are also lvl 25 with autobalance. But they makes only 1 dmg to me and not the normal dmg for that level. But I'm make to much damage. Maybe the creature scalled not normal or an other bug is exist. With other classes, hunter, pala, witcher etc. I get the normal damage. 

If I disable autobalance, the damage ist normal for rogue. 
So I think it is an issue with autobalance module.

I'm sorry for my bad english. :-)
Maybe someone has had similar problems before?

thank you

**Comment by Yehonal** [comment]
Could someone confirm it? can you provide a video?

**Comment by LukasVolgger** [comment]
Yes. This issue happens to me when entering a dungeon with a group member over lvl 80 (255 for Example) or a group member got GM lvl. 
Just play with a normal char and don't cheat so everything is fine

**Comment by Yehonal** [comment]
@LukasVolgger can you confirm this specific case?

```
As example, If I go to Ragefire Chasm as a lvl 25 rogue the creature are also lvl 25 with autobalance. But they makes only 1 dmg to me and not the normal dmg for that level. But I'm make to much damage. Maybe the creature scalled not normal or an other bug is exist. With other classes, hunter, pala, witcher etc. I get the normal damage.
```

**Comment by LukasVolgger** [comment]
Nope, sry didn't test this case. Only my experience in past with this mod

**Comment by pagimu** [comment]
@Yehonal 
I will try to make a video the next days.

@LukasVolgger 
I'm alone int the dungeon with lvl 25. Without any other member and also no GM lvl. A ordinary rogue, alone in a dungeon. 
Without cheating. :-)

**Comment by pagimu** [comment]
Hi everybody, I have tried with a new complied Masterbranch and only the autobalancemodule. The problem still exist. I created a new character. Also a rogue. My first dungeon was the ragefire chasm with lvl 15 and I get only 1 dmg but I make imbalanced damage. My character is not a GM. Without Autobalance all works fine. Other classes works normal. So I think it's a autobalance module issue relatet to rogue. But I don't know what can I do.

**Comment by pagimu** [comment]
Hi all, now I have the same with a warrior. Although it worked before. Maybe I have a missconfiguration of the Module. If it ok, I will attach my AutoBalance.Conf file. It will be very nice if sombody can check my settings. The idea was to use autobalance for single playing and for coop playing with 2 people. Thank you in advanced for your help. 

[AutoBalance.zip](https://github.com/azerothcore/mod-autobalance/files/5162380/AutoBalance.zip)

**Comment by pagimu** [comment]
It is probably a config problem. So I will close that request. Thank you all.
