### ISSUE TITLE
Config: RaidsOnly

### ISSUE THREAD

**Issue by Err0r1** [azerothcore/mod-autobalance#74]
There is a config for DungeonsOnly (no raids are affected)
Can you make an option for RaidsOnly so that only raids are affected and dungeons are not?
Perhaps set in the config which MapID

**Comment by steenburgh** [comment]
As a workaround, you could see if you can set the inflection point for 5-man raids to -0.5. If that's possible, it would make all mobs scale to 99.999%-ish regardless of the number of players.

**Comment by BarbzYHOOL** [comment]
test this guys https://github.com/azerothcore/mod-autobalance/pull/85

**Comment by kjack9** [comment]
This feature request was made obsolete by the `AutoBalance.Enable.*` settings.
