### ISSUE TITLE
Balance module has no effect on ICC gunboat battle damage

### ISSUE THREAD

**Issue by forever2019** [azerothcore/mod-autobalance#75]
This module has no effect on adjusting the damage of ICC gunboat combat. The damage gap between us and the enemy is too big. We were defeated at the beginning of the battle
1. Enable the balance module and log in to the game
2. Enter. Go - 606.3696 2216.8457 199.9909 631
3. Find the gunboat, talk to NPC and start fighting
Request repair

**Comment by littlehelper1987** [comment]
> 
> 
> This module has no effect on adjusting the damage of ICC gunboat combat. The damage gap between us and the enemy is too big. We were defeated at the beginning of the battle
> 
>     1. Enable the balance module and log in to the game
> 
>     2. Enter. Go - 606.3696 2216.8457 199.9909 631
> 
>     3. Find the gunboat, talk to NPC and start fighting
>        Request repair

Confirmed! Hope get fixed :>
