### ISSUE TITLE
The Oculus - final boss's (Ley-Guardian Eregos) stats are not scaled down

### ISSUE THREAD

**Issue by lach3v** [azerothcore/mod-autobalance#82]
As the title says, in The Oculus (Normal), Ley-Guardian Eregos (final boss) stats are not scaled down if the dungeon is entered solo (I haven't tested with more players, or with the Heroic version). 

Not sure if the mod is applying any scaling to this boss at all, but if it does - the scaling is not correct, given the fact that all other bosses in the same dungeon have their HP in the range between 30k-40k, and the end boss's HP is 357k, which makes it impossible for a solo player. His damage is also extreme.

![WoWScrnShot_030721_144215](https://user-images.githubusercontent.com/1040798/110244147-55997480-7f55-11eb-8c41-5ec16a982698.jpg)

**Comment by kjack9** [comment]
This doesn't appear to be an issue in the current version.

![ley-guardian-eregos-scaling](https://github.com/azerothcore/mod-autobalance/assets/19712078/8f2d2425-a627-47c5-8c5e-3e954cbd23cf)

If you have a situation where this is still happening, please re-open this issue.
