### ISSUE TITLE
Module does not work for icc heroic 25 boss kills

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/mod-autobalance#84]
https://github.com/azerothcore/mod-autobalance/blob/4cd8094426398b365c6de1351f005683425be1ce/src/AutoBalance.cpp#L923

when killing a boss in icc 25 heroic / rs 25 heroic this module does not provide a reward

**Comment by pangolp** [comment]
From what they told me, this issue has already been resolved and this is no longer valid. I think it could be closed.
