### ISSUE TITLE
Error on Continuous integration build with modules

### ISSUE THREAD

**Issue by claudiodfc** [azerothcore/mod-autobalance#86]
## Currently all builds are failing due to this module mutex.

Maybe the Ace class was dropped somewhere and someone forgot to change this to std::mutex

`fatal error: use of undeclared identifier 'ACE_Null_Mutex' friend class ACE_Singleton<ABScriptMgr, ACE_Null_Mutex>;`

**Comment by claudiodfc** [comment]
file is AutoBalance.h:10:45

**Comment by FrancescoBorzi** [comment]
@Yehonal

**Comment by SoHigh495** [comment]
Autobalance.cpp 

```
#include "Group.h"

+ABScriptMgr* ABScriptMgr::instance()
+{
+    static ABScriptMgr instance;
+    return &instance;
+}

bool ABScriptMgr::OnBeforeModifyAttributes(Creature *creature, uint32 & instancePlayerCount) {
```

Autobalance.h

Line24:
#define sABScriptMgr ABScriptMgr::instance()

Line: 8
class ABScriptMgr
{
    public: /* Initialization */
        static ABScriptMgr* instance();


        // called at the start of ModifyCreatureAttributes method
