### ISSUE TITLE
Icc spell damage

### ISSUE THREAD

**Issue by svenbledt** [azerothcore/mod-autobalance#89]
The spells in icc do like 3 times more damage then usual. ColdFlame does like 18k 👍🏻 schould do 6k every second. Also the prof's green blub does too much damage and the fontain of the green dragon fight also does to much damage. Sry wrote this on my mobile so maybe someone can help me with this if this maybe is only a config problem. We never get farther than these bosses as theyre just impossible to kill. Ofc marrowgar with the coldflame problem is but with too much high equiped chars.

**Comment by SoHigh495** [comment]
Maybe i have just sone config issues if this could be maybe someone can take a look at my config. Im reachable on discord at Zalacar#1312

**Comment by therelus** [comment]
Yea i tested it too, some Area Damages are x3 than normal , like cold flames and others you mentioned

**Comment by pangolp** [comment]
From what they told me, this issue has already been resolved and this is no longer valid. I think it could be closed.
